productsSample = [
    "LPBank có tiền thân là ngân hàng nào?",
    "Tên chính thức tiếng Anh và mã chứng khoán của LPBank là gì?",
    "Sứ mệnh của LPBank trong việc phát triển kinh tế địa phương là gì?",
    "Các giá trị cốt lõi mà LPBank cam kết thực hiện là gì?",
    "LPBank có những định hướng phát triển như thế nào cho khu vực nông thôn và đô thị?",
    "Tiết kiệm cá nhân tại LPBank có những hình thức nào?",
    "Đặc điểm của sản phẩm tiết kiệm rút gốc linh hoạt là gì?",
    "Lãi suất áp dụng cho tiết kiệm bậc thang có gì đặc biệt?",
    "Tiết kiệm Priority mang lại tiện ích gì cho khách hàng cá nhân?",
    "Các ưu đãi nổi bật khi sử dụng tiết kiệm không kỳ hạn là gì?",
    "Tài khoản An Khang dành cho đối tượng nào?",
    "Dịch vụ mở tài khoản thanh toán online tại LPBank có ưu điểm gì?",
    "Tài khoản lưỡng tính khác biệt như thế nào so với tài khoản thông thường?",
    "Khách hàng có thể lựa chọn tài khoản số đẹp với bao nhiêu chữ số?",
    "Những tiện ích từ dịch vụ ngân hàng số LPBank là gì?",
    "Gói vay nào tại LPBank có lãi suất khởi điểm từ 3.9%/năm?",
    "Điều kiện để khách hàng cá nhân sử dụng thấu chi linh hoạt là gì?",
    "Gói vay sản xuất kinh doanh siêu nhanh được giải ngân trong bao lâu?",
    "Các điều kiện áp dụng cho gói vay tiêu dùng không tài sản đảm bảo là gì?",
    "LPBank có hỗ trợ vay cho sinh viên không, nếu có thì điều kiện là gì?",
    "LPBank đã được trao những giải thưởng nổi bật nào trong năm 2023?",
    "Chỉ số xếp hạng thương hiệu của LPBank đạt bao nhiêu điểm theo Brand Finance?",
    "LPBank được vinh danh ở hạng mục nào trong giải thưởng Asia Pacific Enterprise Award?",
    "Các thành tích liên quan đến trách nhiệm xã hội của LPBank trong giai đoạn 2011–2023 là gì?",
    "Giải thưởng “Ngân hàng số tiêu biểu” được trao cho sản phẩm nào của LPBank?",
    "Bộ giải pháp quản lý doanh thu QR Shop mang lại lợi ích gì cho khách hàng cá nhân?",
    "Các loại tiền tệ hỗ trợ trong dịch vụ tài khoản thanh toán của LPBank là gì?",
    "Phương thức giao dịch và thanh toán trực tuyến nào được LPBank hỗ trợ?",
    "Làm thế nào để sử dụng dịch vụ mở tài khoản số đẹp tại LPBank?",
    "Tiện ích của dịch vụ chuyển tiền quốc tế tại LPBank là gì?",
    "LPBank cung cấp các ưu đãi gì cho cán bộ hưu trí?",
    "Chính sách miễn phí dịch vụ nào áp dụng cho khách hàng cá nhân?",
    "Điều kiện để được miễn phí rút tiền tại ATM LPBank là gì?",
    "Dịch vụ bảo hiểm nào đang được cung cấp cho khách hàng cá nhân tại LPBank?",
    "Làm thế nào để đăng ký nhận lãi suất ưu đãi khi gửi tiết kiệm online?",
    "Tài khoản thanh toán tại LPBank có những tiện ích nào?",
    "Điều kiện và thủ tục đăng ký sử dụng dịch vụ tài khoản số đẹp tại LPBank là gì?",
    "Các hình thức tiết kiệm có kỳ hạn tại LPBank bao gồm những gì?",
    "Khách hàng có thể sử dụng sổ tiết kiệm để làm tài sản đảm bảo không?",
    "LPBank có cung cấp dịch vụ cầm cố sổ tiết kiệm hay không?",
    "Tiện ích của dịch vụ thấu chi linh hoạt tại LPBank là gì?",
    "Các khoản vay tiêu dùng tại LPBank có yêu cầu tài sản đảm bảo không?",
    "Tài khoản tiết kiệm Priority có những ưu điểm gì so với tài khoản tiết kiệm thông thường?",
    "Giải ngân nhanh chóng đối với gói vay tiêu dùng siêu nhanh của LPBank có yêu cầu gì?",
    "Lãi suất áp dụng cho sản phẩm tiết kiệm bậc thang tại LPBank là bao nhiêu?",
    "Tài khoản thanh toán tại LPBank có những tiện ích gì cho khách hàng doanh nghiệp?",
    "Các sản phẩm tiết kiệm phù hợp với khách hàng cá nhân nào tại LPBank?",
    "LPBank có hỗ trợ vay tiêu dùng đối với cán bộ, công chức, viên chức không?",
    "LPBank có cung cấp dịch vụ thanh toán quốc tế như thế nào?",
    "Điều kiện để vay mua nhà đất tại LPBank là gì?",
    "Các dịch vụ hỗ trợ khách hàng trực tuyến của LPBank bao gồm những gì?",
    "LPBank hỗ trợ gì cho các hộ kinh doanh cá nhân trong việc quản lý doanh thu?",
    "Tài khoản lưỡng tính tại LPBank có những đặc điểm gì nổi bật?",
    "Các dịch vụ tiết kiệm có kỳ hạn tại LPBank phù hợp với đối tượng khách hàng nào?",
    "Năm thành lập và ngân hàng tiền thân của LPBank là gì?",
    "LPBank chính thức được đổi tên thương mại từ ngày nào?",
    "Số vốn điều lệ hiện tại của LPBank là gì?",
    "LPBank xây dựng thương hiệu dựa trên những giá trị nào?",
    "LPBank hướng đến những mục tiêu chiến lược nào trong quá trình phát triển?",
    "Những sản phẩm tiết kiệm nào được LPBank cung cấp cho khách hàng cá nhân?",
    "Điểm khác biệt giữa tiết kiệm rút gốc linh hoạt và tiết kiệm bậc thang là gì?",
    "Khách hàng có thể mở tài khoản tiết kiệm online qua ứng dụng LPBank như thế nào?",
    "Lãi suất áp dụng cho tiết kiệm không kỳ hạn tại LPBank được tính như thế nào?",
    "Tiết kiệm bảo toàn có những tiện ích gì cho khách hàng?",
    "Tài khoản An Khang mang lại những ưu đãi gì cho người hưu trí?",
    "LPBank cung cấp dịch vụ tài khoản số đẹp với những đặc điểm nào?",
    "Các đối tượng khách hàng nào phù hợp với tài khoản lưỡng tính?",
    "Bộ giải pháp QR Shop hỗ trợ gì cho khách hàng là chủ hộ kinh doanh?",
    "Các tiện ích khi mở tài khoản thanh toán tại LPBank là gì?",
    "Gói giải pháp vay mua nhà đất tại LPBank có lãi suất khởi điểm là bao nhiêu?",
    "Thấu chi linh hoạt áp dụng cho đối tượng khách hàng nào?",
    "Các điều kiện để vay tiêu dùng không tài sản đảm bảo tại LPBank là gì?",
    "LPBank cung cấp các gói vay hỗ trợ khởi nghiệp cho sinh viên như thế nào?",
    "Lợi ích của gói vay mua xe ô tô nhanh tại LPBank là gì?",
    "Dịch vụ nhận/chuyển tiền quốc tế của LPBank hoạt động như thế nào?",
    "Khách hàng có thể sử dụng dịch vụ ngân hàng số LPBank để thực hiện những giao dịch gì?",
    "Bảo hiểm do LPBank cung cấp có bao nhiêu loại hình?",
    "Dịch vụ ngoại hối tại LPBank hỗ trợ các giao dịch bằng những loại tiền nào?",
    "Điều kiện để mở tài khoản và sử dụng các dịch vụ tại LPBank là gì?",
    "LPBank đạt được những giải thưởng quan trọng nào trong lĩnh vực ứng dụng công nghệ?",
    "Tại sao LPBank được công nhận là một trong 100 ngân hàng lớn nhất ASEAN?",
    "Các đóng góp của LPBank trong lĩnh vực trách nhiệm xã hội (CSR) được đánh giá như thế nào?",
    "Những bước tiến nổi bật của LPBank trong việc phát triển ứng dụng ngân hàng di động là gì?",
    "Giá trị thương hiệu của LPBank được Brand Finance định giá vào năm 2023 là bao nhiêu?"
]



chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?","Hôm nay trời có mây không?",
    "Mặt trời sẽ mọc lúc mấy giờ ngày mai?",
    "Nhiệt độ thấp nhất ngày hôm nay là bao nhiêu?",
    "Bạn có biết khi nào sẽ có tuyết không?",
    "Cuối tuần này thời tiết ở thành phố Hồ Chí Minh thế nào?",
    "Gió ngoài trời đang thổi mạnh bao nhiêu km/h?",
    "Độ ẩm hiện tại là bao nhiêu phần trăm?",
    "Có khả năng xảy ra sấm sét vào tối nay không?",
    "Mặt trời lặn lúc mấy giờ hôm nay?",
    "Bạn có thể dự đoán thời tiết cho tuần sau không?",
    "Ai đã viết bài hát quốc ca Việt Nam?",
    "Leonardo da Vinci sinh vào năm nào?",
    "Lịch sử của máy tính bắt đầu từ khi nào?",
    "Ai là nhà khoa học đầu tiên phát hiện ra lực hấp dẫn?",
    "Thành phố nào lớn nhất thế giới theo diện tích?",
    "Bạn có thể kể tôi về nguồn gốc của Google không?",
    "Sự kiện nào dẫn đến kết thúc Chiến tranh Lạnh?",
    "Người đầu tiên đặt chân lên Mặt Trăng là ai?",
    "Bạn được lập trình bằng ngôn ngữ nào?",
    "Làm thế nào để bạn hoạt động?",
    "Bạn có thể tính 234 x 56 giúp tôi không?",
    "Thực vật sống ở sa mạc có gì đặc biệt?",
    "Biển nào sâu nhất thế giới?",
    "Tại sao bầu trời có màu xanh?",
    "Làm thế nào để học lập trình nhanh chóng?",
    "Bộ truyện 'Harry Potter' được viết bởi ai?",
    "Động vật nào nhanh nhất trên cạn?",
    "Bạn có thể giải thích cơ chế hoạt động của xe điện không?",
    "Kinh tế của Việt Nam trong năm nay phát triển thế nào?",
    "Bức tranh nổi tiếng nhất của Van Gogh là gì?"
]